version: '3.7'

services:
  db:
    image: informaticsmatters/rdkit-cartridge-debian
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  genui:
    image: sichom/genui:${DOCKER_IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - DJANGO_SETTINGS_MODULE
      - GENUI_BACKEND_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PASSWORD
      - REACT_APP_GENUI_BACKEND_ROOT_URL=${GENUI_BACKEND_PROTOCOL}://${GENUI_BACKEND_HOST}:${GENUI_BACKEND_PORT}/
      - GENUI_FRONTEND_APP_PATH
      - PUBLIC_URL=${GENUI_FRONTEND_APP_PATH}
      - GENUI_USER
      - GENUI_USER_GROUP
    entrypoint: /code/entrypoint.sh
    command: gunicorn --certfile=/etc/certs/${GENUI_BACKEND_HOST}.crt --keyfile=/etc/certs/${GENUI_BACKEND_HOST}.key genui.wsgi:application --bind 0.0.0.0:${GENUI_BACKEND_PORT}
    volumes:
      - ${GENUI_DATA_MOUNT}/media:/code/src/genui/media/
      - static:/code/src/genui/static/
      - frontend:/code/src/genui_gui/build/
      - ./config/nginx/certs/:/etc/certs
      - ${DOCKER_USER_CONFIG_MOUNT}/group:/etc/group:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/passwd:/etc/passwd:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/shadow:/etc/shadow:ro
    expose:
      - ${GENUI_BACKEND_PORT}
    depends_on:
      - db
      - redis
  celery:
    image: sichom/genui:${DOCKER_IMAGE_TAG}
    environment:
      - DJANGO_SETTINGS_MODULE
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - GENUI_BACKEND_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - REDIS_HOST
      - REDIS_PASSWORD
      - GENUI_USER
      - GENUI_USER_GROUP
    command: wait-for-it genui:${GENUI_BACKEND_PORT} -t 3600 -- celery worker -c ${GENUI_CELERY_CONCURRENCY} -Q ${GENUI_CELERY_QUEUES} -E -A genui --loglevel=info --hostname celery@%h
    volumes:
      - ${GENUI_DATA_MOUNT}/media:/code/src/genui/media/
      - ${DOCKER_USER_CONFIG_MOUNT}/group:/etc/group:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/passwd:/etc/passwd:ro
      - ${DOCKER_USER_CONFIG_MOUNT}/shadow:/etc/shadow:ro
    depends_on:
      - genui
#  # use this to define a periodic task
#  celery-beat:
#    build: .
#    command: celery -A proj beat -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - genui_db
#      - redis
  nginx:
    image: nginx:latest
    environment:
      - GENUI_BACKEND_PROTOCOL
      - GENUI_BACKEND_HOST
      - GENUI_BACKEND_PORT
      - GENUI_FRONTEND_APP_PATH
    command: /bin/bash -c "envsubst '$$GENUI_BACKEND_PROTOCOL $$GENUI_BACKEND_HOST $$GENUI_BACKEND_PORT $$GENUI_FRONTEND_APP_PATH' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${GENUI_DATA_MOUNT}/media:/usr/share/nginx/html/downloads:ro
      - static:/usr/share/nginx/html/static:ro
      - frontend:/usr/share/nginx/html/app:ro
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - genui

volumes:
  data:
  static:
  frontend:

# DOCKER_NET_MTU=1442 must be set so that the app works on the openstack cloud
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: ${DOCKER_NET_MTU}
