name: genui
channels:
  - conda-forge
  - rdkit
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h6cacc03_7
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.16.0=ha00ac49_1009
  - certifi=2021.10.8=py39hf3d152e_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.4.7=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.96=h8e229c2_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - greenlet=1.1.2=py39he80948d_1
  - icu=69.1=h9c3ff4c_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.3.2=py39h1a9c180_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libdeflate=1.10=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_13
  - libgfortran-ng=11.2.0=h69a702a_13
  - libgfortran5=11.2.0=h5c6108e_13
  - libglib=2.70.2=h174f98d_4
  - libgomp=11.2.0=h1d223b6_13
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_13
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.1=py39h2fa2bec_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h9c3ff4c_0
  - numpy=1.22.3=py39h18676bf_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py39hde0f152_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.0.1=py39hae2aec6_2
  - pip=22.0.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.21.0=py39h0934665_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - python=3.9.10=hc74c709_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - rdkit=2021.03.5=py39hccf6a74_0
  - readline=8.1=h46c0cb4_0
  - reportlab=3.5.68=py39he59360d_1
  - setuptools=60.9.3=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.32=py39hb9d737c_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.12=h27826a3_0
  - tzdata=2021e=he74cb21_0
  - unicodedata2=14.0.0=py39h3811e60_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
prefix: /home/sichom/software/miniconda/envs/genui
